{ pkgs, lib, ... }:

{
  environment.systemPackages = with pkgs; [
    vim
    wget
    git
    gh
    htop
    udevil
    usbutils

    klipper
    klipper-flash
    klipper-firmware
    klipper-genconf
    klipper-estimator

    octoprint
    moonraker

    python3
    pkgsCross.avr.stdenv.cc
    gcc-arm-embedded
    bintools-unwrapped
    libffi
    libusb1
    avrdude
    stm32flash
    pkg-config
    python313Packages.pyserial
    ncurses
  ];


  # ============================================================
  # KLIPPER
  # ============================================================

  services.klipper = {
    enable = true;

    configFile = "/home/flake/Home_Flake/modules/printer.cfg";

    inputTTY = "/tmp/printer";

    octoprintIntegration = true;

    logFile = "/tmp/klippy.log";

    mutableConfig = true;
  };


  # ============================================================
  # OCTOPRINT
  # ============================================================

  services.octoprint = {
    enable = true;

    openFirewall = false;

    plugins = plugins: with plugins; [
      octoklipper
      themeify
      psucontrol
      simpleemergencystop
      bedlevelvisualizer
      printtimegenius
      gcodeeditor
    ];

    group = "wheel";

    # OctoPrint itself does NOT own port 5000.
    # Port 5000 belongs to the systemd socket.
    host = "127.0.0.1";

    port = 5001;

    extraConfig = {
      server = {
        baseurl = "/octoprint";
      };

      webcam = {
        stream = "http://127.0.0.1:40000/?action=stream";
      };

      reverseProxy = {
        trustedProxies = [
          "127.0.0.1"
          "192.168.1.0/24"
        ];
      };
    };
  };


  # ============================================================
  # MJPG-STREAMER
  # ============================================================

  services.mjpg-streamer = {
    enable = true;

    group = "video";

    inputPlugin =
      "input_uvc.so -d /dev/video0 -r 640x480 -f 30 -yuv";

    outputPlugin =
      "output_http.so -w @www@ -p 40000 -l 127.0.0.1";
  };


  # ============================================================
  # DO NOT START THE PRINTER SERVICES AT BOOT
  #
  # The services still exist and are fully generated by NixOS.
  # We are only removing their normal multi-user.target startup.
  # ============================================================

  systemd.services.klipper.wantedBy = lib.mkForce [ ];

  systemd.services.octoprint.wantedBy = lib.mkForce [ ];

  systemd.services.mjpg-streamer.wantedBy = lib.mkForce [ ];


  # ============================================================
  # SOCKET ACTIVATION
  #
  # Nginx -> 127.0.0.1:5000
  #
  # Nothing needs to be running on 5000 until something connects.
  # ============================================================

  systemd.sockets."3d-printer-stack" = {
    description = "3D Printer Stack Socket";

    wantedBy = [ "sockets.target" ];

    socketConfig = {
      ListenStream = "127.0.0.1:5000";
      Accept = false;
      NoDelay = true;
    };
  };


  # ============================================================
  # SOCKET-ACTIVATED PRINTER PROXY
  #
  # The socket activation starts this service.
  #
  # The service then requires the actual printer services and
  # proxies traffic from port 5000 -> OctoPrint port 5001.
  # ============================================================

  systemd.services."3d-printer-stack" = {
    description = "3D Printer Stack";

    requires = [
      "klipper.service"
      "octoprint.service"
      "mjpg-streamer.service"
    ];

    after = [
      "klipper.service"
      "octoprint.service"
      "mjpg-streamer.service"
    ];

    serviceConfig = {
      Type = "simple";

      ExecStartPre =
        "${pkgs.bash}/bin/bash -c '" +
        "for i in $(seq 1 60); do " +
        "${pkgs.curl}/bin/curl -fsS http://127.0.0.1:5001/ " +
        ">/dev/null 2>&1 && exit 0; " +
        "sleep 1; " +
        "done; " +
        "echo \"OctoPrint failed to become ready\"; " +
        "exit 1'";

      ExecStart =
        "${pkgs.systemd}/lib/systemd/systemd-socket-proxyd " +
        "127.0.0.1:5001";

      Restart = "on-failure";
      RestartSec = "5s";
    };
  };


  # ============================================================
  # PRINTER TRAFFIC MONITOR
  #
  # Every minute, look at the most recent OctoPrint request.
  # If there has been no request for an hour, shut everything down.
  # ============================================================

  systemd.services."3d-printer-idle-check" = {
    description = "Check 3D Printer Stack for inactivity";

    serviceConfig = {
      Type = "oneshot";
    };

    script = ''
      set -eu

      STACK="3d-printer-stack.service"

      if ! ${pkgs.systemd}/bin/systemctl is-active --quiet "$STACK"; then
        exit 0
      fi

      LOG="/var/log/nginx/access.log"

      if [ ! -f "$LOG" ]; then
        exit 0
      fi

      LAST_LINE=$(
        ${pkgs.gnugrep}/bin/grep '"/octoprint/' "$LOG" |
        ${pkgs.coreutils}/bin/tail -1 ||
        true
      )

      if [ -z "$LAST_LINE" ]; then
        echo "No OctoPrint traffic found."
        exit 0
      fi

      # Extract nginx's timestamp:
      # [13/Sep/2026:11:30:42 -0400]
      TIMESTAMP=$(
        echo "$LAST_LINE" |
        ${pkgs.gawk}/bin/awk -F'[][]' '{print $2}'
      )

      LAST_REQUEST=$(
        ${pkgs.coreutils}/bin/date -d "$TIMESTAMP" +%s
      )

      NOW=$(${pkgs.coreutils}/bin/date +%s)

      IDLE_TIME=$((NOW - LAST_REQUEST))

      echo "Last OctoPrint request was $IDLE_TIME seconds ago."

      if [ "$IDLE_TIME" -ge 3600 ]; then
        echo "3D Printer Stack idle for one hour. Stopping."

        ${pkgs.systemd}/bin/systemctl stop \
          3d-printer-stack.service \
          octoprint.service \
          klipper.service \
          mjpg-streamer.service
      fi
    '';
  };


  # ============================================================
  # IDLE CHECK TIMER
  # ============================================================

  systemd.timers."3d-printer-idle-check" = {
    description = "Check 3D Printer Stack inactivity";

    wantedBy = [ "timers.target" ];

    timerConfig = {
      OnBootSec = "5min";
      OnUnitActiveSec = "1min";
      Unit = "3d-printer-idle-check.service";
    };
  };
}